# Generated by Django 2.1 on 2019-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
