# Generated by Django 2.1 on 2019-07-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190710_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='chat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.ChatModel'),
        ),
    ]
